### ISSUE TITLE
Omit NA data first

### ISSUE THREAD

**Issue by ballen2024** [introdsci/DataScience-mnmenator#1]
Since we usually will omit NA data points, it might save time in the cleaning process to do this first by using dplyr's na.omit function

https://github.com/introdsci/DataScience-mnmenator/blob/3738ca8ce9a3747bb0aa61649d4c1ade5a838b2c/deliverable1.Rmd#L176

**Comment by mnmenator** [comment]
In this case NA does represent usable data, so it is being converted to another value rather than omitted.
